## Numpy

In [10]:
import numpy as np

##### Numpy Arrays

In [ ]:
#create 2d array
arr = np.array([[0, 1, 2], [3, 4, 5]])
#create 2d array with dtype
arr = np.array([[0, 1, 2], [3, 4, 5]],dtype=np.float32)
#cast np array to other dtype
arr = arr.astype(np.float32)
#copy np array
arr1 = arr #arr1 is reference to arr
arr2 = arr.copy() #arr2 is clone of arr
#Use Nan
arr = np.array([np.nan, 1, 2])
#Use Infinity
np.inf #positive
-np.inf #negative

#zeros & ones
arr = np.zeros(4)
arr = np.ones((2, 3), dtype=np.int32)

arr = np.zeros_like(arr) #create ones array using dimension of some other array
arr = np.ones_like(arr, dtype=np.int32)

##### Manipulation

In [ ]:
#fill diagonal entries
np.fill_diagonal(data, 0)

In [ ]:
#reshaping data
reshaped_arr = np.reshape(arr, (2, 4))
reshaped_arr = np.reshape(arr, (-1, 2, 2)) #-1=>automatically set this value (possible to set -1 for atmost 1 dimension)

#to flatten data to 1D
flattened = arr.flatten()

#concatenate
np.concatenate([arr1, arr2])
np.concatenate([arr1, arr2], axis=1)

In [ ]:
#transposing
transposed = np.transpose(arr, axes=(1, 0, 2)) #transpose 1st dim to 2nd, 2nd to 1st, and don't transpose 3rd

##### Ranges

In [ ]:
#ranges in numpy - use arange function
arr = np.arange(a)
arr = np.arange(a, b, step_size, dtype=np.float32)

#linspace
arr = np.linspace(a, b, num=number_of_values_needed, endpoint=False, dtype=np.int32) #endpoint - incl/excl b

##### Math

In [ ]:
#array math
arr = np.array([[1, 2], [3, 4]])
# Add 1 to element values
print(repr(arr + 1))
# Subtract element values by 1.2
print(repr(arr - 1.2))
# Double element values
print(repr(arr * 2))
# Halve element values
print(repr(arr / 2))
# Integer division (half)
print(repr(arr // 2))
# Square element values
print(repr(arr**2))
# Square root element values
print(repr(arr**0.5))

#It is important to note that performing arithmetic on NumPy arrays does not change the original array, and instead produces a new array that is the result of the arithmetic operation.

# Raised to power of e
print(repr(np.exp(arr)))
# Raised to power of 2
print(repr(np.exp2(arr)))
# Raise 3 to power of each number in arr
print(repr(np.power(3, arr)))
# Raise arr2 to power of each number in arr
print(repr(np.power(arr2, arr)))

arr2 = np.array([[1, 10], [np.e, np.pi]])
# Natural logarithm
print(repr(np.log(arr2)))
# Base 10 logarithm
print(repr(np.log10(arr2)))

#matrix maths operations

#dot product or matrix multiplication
arr = np.matmul(arr1, arr2)

###### Random

In [ ]:
#Random
print(np.random.randint(5))
print(np.random.randint(5, high=6))
random_arr = np.random.randint(-3, high=14, size=(2, 2))

#set random seed
np.random.seed(42)

#randomly shuffle array
np.random.shuffle(arr)

#draw random from a probaility distribution
#from uniform
arr = np.random.uniform(low=-3.4, high=5.9, size=(2, 2))
#from gaussian
arr = np.random.normal(loc=-2.4, scale=4.0, size=(2, 2)) #loc->mean scale->std deviation
#from custom distribution
arr = np.random.choice(inp, size=(2, 2), p=[0.8, 0.19, 0.01]) #p.shape()=inp.shape() and sum(p)= 1

###### Indexing and slicing

In [1]:
#indexing in numpy
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(repr(arr[:]))
print(repr(arr[1:]))
print(repr(arr[:, -1]))
print(repr(arr[:, 1:]))
print(repr(arr[0:1, 1:]))
print(repr(arr[0, 1:]))

<IPython.core.display.Javascript object>

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])
array([[4, 5, 6],
       [7, 8, 9]])
array([3, 6, 9])
array([[2, 3],
       [5, 6],
       [8, 9]])
array([[2, 3]])
array([2, 3])


#### Argmin and argmax

In [ ]:
#argmax and argmin -> return index number in flattened version of arr
np.argmin(arr)
np.argmax(arr)
np.argmin(arr, axis=0) #row axis
np.argmin(arr, axis=1) #col axis
np.argmin(arr, axis=-1) #last axis. In this case it is the column axis. In 3D it is Z axis

###### Filtering

In [2]:
#Filtering in numpy
arr = np.array([[0, 2, 3],
                [1, 3, -6],
                [-3, -2, 1]])
print(repr(arr == 3))
print(repr(arr > 0))
print(repr(arr != 1))
print(repr(~(arr != 1)))

<IPython.core.display.Javascript object>

array([[False, False,  True],
       [False,  True, False],
       [False, False, False]])
array([[False,  True,  True],
       [ True,  True, False],
       [False, False,  True]])
array([[ True,  True,  True],
       [False,  True,  True],
       [ True,  True, False]])
array([[False, False, False],
       [ True, False, False],
       [False, False,  True]])


In [3]:
#to figure out nan values
arr = np.array([[0, 2, np.nan],
                [1, np.nan, -6],
                [np.nan, -2, 1]])
print(repr(np.isnan(arr)))

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([[False, False,  True],
       [False,  True, False],
       [ True, False, False]])


In [8]:
#np.where -> use to returns indexes of elements that match the filter
x_ind, y_ind = np.where(arr != 0)

#use np.where for true replacement and false replacement values
arr = np.array([[-2, 5], 
                [-1, 8]])
positives = np.ones_like(arr)
negatives = -np.ones_like(arr)
print(np.where(arr>=0, positives, negatives))
print(np.where(arr>=0, '+ve', '-ve')) #also called broadcasting 

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[[-1  1]
 [-1  1]]


<IPython.core.display.Javascript object>

[['-ve' '+ve']
 ['-ve' '+ve']]


In [ ]:
#axis-wise filtering
np.any(arr > 0) # ||
np.all(arr > 0) # &&
np.any(arr > 0, axis=0) #if any row
np.any(arr > 0, axis=1) #if any column

##### Statistics and aggregation

In [ ]:
#statistics in Numpy

#min and max
arr.min()
arr.max()
arr.min(axis=0)
arr.max(axis=1)

#statistical metrics
#mean
np.mean(arr)
mean_x = np.mean(x)
mean_x_nan = np.nanmean(x_nan) #in case the data contains Nan values

#median
np.median(arr)
np.nanmedian(arr)

#variance
np.var(arr)
mean_x_nan = np.nanvar(x_nan, ddof = 1) #in case the data contains Nan values

#std deviation
variance_x = np.std(x)
mean_x_nan = np.nanstd(x_nan, ddof = 1) #ddof - degree of freedem

#covariance
cov_xy = np.cov(x,y) #this will return the covariance matrix of x,y containing x_variance, y_variance on diagonal elements and covariance of x,y

#correlation
corr = np.corrcoef(x,y)





In [ ]:
#distributions
#binomial
X = np.random.binomial(n,p,N)

#poisson
X = np.random.poisson(lambda_,N)

#normal
X = np.random.normal(mu,sigma,N)





##### File IO

In [ ]:
#saving data
#gets saved in .npy file
np.save('file/path/name.npy', arr)

#loading data
load_arr = np.load('arr.npy')